# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set environment variable to skip Puppeteer download
ENV PUPPETEER_SKIP_DOWNLOAD=true

# Create app directory
WORKDIR /app

# Copy dependency files and TypeScript config
COPY package.json package-lock.json tsconfig.json ./

# Copy source
COPY src ./src

# Install dependencies without running scripts, compile TypeScript, and set execute permission
RUN npm install --ignore-scripts \
    && npx tsc --outDir build --rootDir src \
    && chmod +x build/index.js

# Default command to start the MCP server
CMD ["node", "build/index.js"]
